spring:
  application:
    name:todo-list
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=todo_list
    username: postgres
    password: tjdgus123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # create, update, validate, none ? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT 설정
jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationAndValidationPleaseChangeThisInProduction123456789}
  expiration: 86400000  # 24시간 (밀리초)
  refresh-expiration: 604800000  # 7일 (밀리초)